/*
 * Copyright 2025 TomTom N.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package types

import (
	"github.com/tomtom-international/macos-actions-runner-controller/pkg/core/types"
	"github.com/tomtom-international/macos-actions-runner-controller/pkg/prober/probe"
	"github.com/tomtom-international/macos-actions-runner-controller/pkg/utils"
	"time"
)

// TODO: Document event types
// Event types
const (
	// EventRunnerCreated represents the event type for a runner creation.
	// StateMachine sends this event when it adds a new runner.
	// Receiver: RunnerWorker will trigger on that event.
	EventRunnerCreated = "runner_created"

	// EventRunnerStopRequest represents the event type for a runner stop request.
	// Sender: StateMachine sends this event when the runner have to be stopped
	// Receiver: RunnerWorker will trigger on that event.
	EventRunnerStopRequest = "runner_stop_request"

	EventRunnerStatusUpdated = "runner_status_updated"

	EventRunnerLivenessHealthCheck = "runner_liveness_healthcheck"

	EventRunnerStartupHealthCheck = "runner_startup_healthcheck"
)

type RunnerStatus string

const (
	Created  RunnerStatus = "created"
	Stopped  RunnerStatus = "stopped"
	Stopping RunnerStatus = "stopping"
	Running  RunnerStatus = "running"
	Failed   RunnerStatus = "failed"
	Finished RunnerStatus = "finished"
)

type Runner struct {
	// ID is a unique identifier of the runner.
	// Generated by the StateMachine when the runner is added to Tarter Standalone mode or
	// provided by the Controller when Tarter fetching runner info in Managed mode.
	ID            utils.UID          `json:"id"`
	GhaRunnerName string             `json:"ghaRunnerName,omitempty"`
	Config        types.RunnerConfig `json:"config,omitempty"`
}

type RunnerState struct {
	Runner       *Runner           `json:"runner"`
	Status       RunnerStatus      `json:"status"`
	ErrorMessage string            `json:"errorMessage,omitempty"`
	CreatedAt    time.Time         `json:"createdAt,omitempty"`
	StartedAt    time.Time         `json:"startedAt,omitempty"`
	EndedAt      time.Time         `json:"endedAt,omitempty"`
	Health       RunnerHealthState `json:"health,omitempty"`
}

// RunnerStateList is list of simplified version of RunnerState used to preview the state of the runners in State.
type RunnerStateList struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	GhaRunnerName string `json:"ghaRunnerName"`
	Status        string `json:"status"`
	ErrorMessage  string `json:"errorMessage,omitempty"`
}

type RunnerHealthState struct {
	Startup  probe.Result `json:"startup,omitempty"`
	Liveness probe.Result `json:"liveness,omitempty"`
}

type HealthCheckEventPayload struct {
	RunnerID     utils.UID
	HealthResult probe.Result
}
