name: Publish Release Artifacts

on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.release_version.outputs.release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      - name: Set version from release
        id: release_version
        run: |
          echo "release_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

  publish-artifacts:
    name: Build and Release Artifacts
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache: true

      - name: Build Release artifacts
        run: make release VERSION=${{ needs.setup.outputs.release_version }}

      - name: Upload Release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          tag_name: ${{ github.event.release.tag_name }}
          append_body: true

  publish-images:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build and Push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: make docker VERSION=${{ needs.setup.outputs.release_version }} IMAGE_REPO="${{ env.REGISTRY }}/${{ vars.AWS_ECR_REPO}}"

  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs:
      - setup
      - publish-artifacts
      - publish-images
    steps:
      - name: Job summary
        run: |
          echo "The [publish.yaml](https://github.com/tomtom-international/macos-actions-runner-controller/blob/main/.github/workflows/publish.yaml) workflow has been triggered!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Parameters:**" >> $GITHUB_STEP_SUMMARY
          echo "- version: ${{ needs.setup.outputs.release_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- sha: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY